[[redirects]]
  from = "/"
  to = "/startup/"
  status = 301
  forece = true

[[redirects]]
  from = "/"
  to = "/dado/"
  status = 301
  forece = true

[[redirects]]
  from = "/"
  to = "/restaurante/"
  status = 301
  forece = true

[[redirects]]
  from = "/"
  to = "/formulario/"
  status = 301
  forece = true